name: base
channels:
  - bioconda
  - defaults
dependencies:
  - scipy=1.9.3=py39h3d31255_0
  - pip:
      - simpervisor==0.4
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - streamlit==1.23.1
      - tenacity==8.2.2
      - terminado==0.17.1
      - tinycss2==1.2.1
      - toml==0.10.2
      - tornado==6.2
      - traitlets==5.9.0
      - typing-extensions==4.6.3
      - validators==0.20.0
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - yarl==1.8.2
      - zipp==3.15.0
